### ISSUE TITLE
Express goal of folding into URL Standard

### ISSUE THREAD

**Issue by annevk** [WICG/urlpattern#17]
A generic URL pattern match library would most logically fit into the URL Standard I think, especially if we want to more deeply consider shorthand syntax and such.

Given that scope it might also be worth adjusting the name and such some. At least from the meeting it seemed clear that beyond service worker scope, filtering in the service worker fetch event was also considered an important use case with somewhat different requirements.

**Comment by wanderview** [comment]
I think standardization is an explicit goal, but it I'm not sure that we've settled on a final place for the spec to live.  While URLPattern is clearly related to URL, I'm not sure I'm sold that there is a benefit to adding it on to the URL spec.  Indeed, I think it would be easier to digest them separately instead of in one large super spec.  Also that would be easier to do since we are starting in WICG and then moving to another venue after incubation.  A separate spec would just be a move instead of having to integrate two spec's into one.

**Comment by wanderview** [comment]
Maybe we could have a sentence that says this proposal hopes to move into the whatwg URL workstream.  That leaves the question of combined vs separate specs to later.
